version: '3.10'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrollplatform
    ports:
      - "8000:8000"  
    volumes:
      - .:/app  
    environment:
      - DJANGO_SETTINGS_MODULE=scrollplatform.settings  
      - PYTHONUNBUFFERED=1                     
    command: >
      sh -c "cd /app/scrollplatform &&
             gunicorn scrollplatform.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:1.25-alpine 
    container_name: scrollplatform_nginx
    ports:
      - "81:80"  # 80 to 8000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # volume config file
      - ./scrollplatform/static:/app/scrollplatform/static  # volume static files
      - ./scrollplatform/media:/app/scrollplatform/media  # volume media files
    depends_on:
      - web  # depends on web 



# To run the docker-compose file, use the following command:
#docker-compose up --build  